
/****************************************************************************
 * THIS FILE IS AUTOGENERATED BY CMAKE. DO NOT EDIT!
 ****************************************************************************/

/* Changes to the configuration reflected here can be made with ccmake on
 * unix or with cmake-gui on windows. Alternatively you can use cmake's -D
 * or -P switches to set some configuration values at cmake configuration time.
 */

#ifndef BTC_CONFIG
#define BTC_CONFIG 1

#define BTC_DISABLE_MSVC_WARNINGS

#endif
